all: task2-1-sync task2-2-sync task2-3-sync
task2-1-sync: task2-1-sync.cpp
	g++ task2-1-sync.cpp -o task2-1-sync
task2-2-sync: task2-2-sync.cpp
	g++ task2-2-sync.cpp -o task2-2-sync
task2-3-sync: task2-3-sync.cpp
	g++ task2-3-sync.cpp -o task2-3-sync