all: task2-1-async task2-2-async task2-3-async
task2-1-async: task2-1-async.cpp
	g++ task2-1-async.cpp -o task2-1-async
task2-2-async: task2-2-async.cpp
	g++ task2-2-async.cpp -o task2-2-async
task2-3-async: task2-3-async.cpp
	g++ task2-3-async.cpp -o task2-3-async